language: php

php:
- '7.1'
env:
  global:
  - ZIP_FILENAME=list-locations-bmlt-build${TRAVIS_BUILD_NUMBER}-${TRAVIS_COMMIT}.zip
  - S3_BUCKET=archives.bmlt.app
  - S3_KEY=list-locations-bmlt
jobs:
  include:

  - stage: lint
    install:
    - composer install
    script:
    - find . -name "*.php" ! -path '*/vendor/*' -print0 | xargs -0 -n1 -P8 php -l
    - vendor/squizlabs/php_codesniffer/bin/phpcs --warning-severity=6 --standard=PSR2 --ignore=vendor --extensions=php --report=summary ./
  - stage: zip file
    env:
    - BUILD_DIR=build
    - DIST_DIR_S3=dist/s3
    - DIST_DIR_GITHUB=dist/github
    - GITHUB_RELEASE_FILENAME=list-locations-bmlt.zip
    script:
    - find ./ -type d | xargs chmod 755
    - find ./ -name '*.php' | xargs chmod 644
    - zip -r $ZIP_FILENAME list-locations && mkdir $BUILD_DIR && mv $ZIP_FILENAME $BUILD_DIR/
    before_deploy:
    - chmod +x travis/deploy-wordpress.sh
    - mkdir -p $DIST_DIR_S3 && cp $BUILD_DIR/$ZIP_FILENAME $DIST_DIR_S3/$ZIP_FILENAME
    - mkdir -p $DIST_DIR_GITHUB && cp $BUILD_DIR/$ZIP_FILENAME $DIST_DIR_GITHUB/$GITHUB_RELEASE_FILENAME
    deploy:
    - provider: s3
      access_key_id: AKIAI7JHYFA6DI3WYP5A
      secret_access_key:
        secure: JqoWw6CjpSV4gx1XelXCDfst2iao9z4FTlsYtHw2Z8m2ONYV7eRh6GiW38MotoQL5sd7qyBhwVbbC/JbNSZbaDxDqTB6kUYut/0jxjPYrzqsaog9JcFcq3q1usu/YYNLf3qYafnZumTT7XayuH19x8nyFBlxQZuVvyvuvcc6kZsFx98wl54LwJE+EI4+QIawaJR2GoItoot5lpvSbk04IByqkZyv1iOsGKegWv1zFQlziOnI6fFxf6/lDSdKPpl86VWsrQcC16AniLWLU7EYMby02gwQVw2TZsWjRmg4BL8vvsTC04A06Z0sASSli8dAjZH8oidbUZbZde9+rZAaCQizfeTLsF6aE59knBcVBl+skHkD0+zitGnkH4azl4gndXX8TX0BeEV869I2EgFOPwSWQXCdV3cKexcTpsYatcvbaAoPDODmZbmzIyzIV/20p2hLWrkd+3M4InXeElfr6Grftri6QHXg8re8aCrCrHipI/M2Zd2X5KASRnWlNk6VzJz7Swyuw7Ctm4c6d7Iz5/O9me5+/qK2OGfVGDC3lMC/P/3rGovEJPtKxBaPT+t+N901VeummJFMkIOeEEV1WzvSsh7mmQEIBxcbERFnaCTwb3Ipcu5Le5OUvMsLhyT2hwEIujfo0hpOuqPzGo1Zmbp+woI3x8fXF/497DvHBoQ=
      bucket: "$S3_BUCKET"
      local_dir: "$DIST_DIR_S3"
      upload-dir: "$S3_KEY"
      skip_cleanup: true
      on:
        all_branches: true
    - provider: releases
      api_key:
        secure: hO9+/QLHuE+W9ApaBvjRdTDLq50IzuZ4K8jUK2gJUOltKxJSaIAgMprXFb3C56CpV0kvJzNFBfyBMb6v8zjF7lqxFiJ5L54XNEdSw9F41gpGXCeJqj+nXvAdVCdJAc0ccfwlfUFEp4wA9YjtmtvKukNif3/gk8aI44RAbjy6TDnMM/nkI2BegjE3XOP66cfxSB3aUA79mNNDma1q9HJ94r/sYsqIVYDkouQCbVNxAPQIAv4eVrlop7wsP5eEpOv8+VXZWPjJCSGl5vWMeBwectPEXWF4ZPy9Uz6XL3HgDppxcM5Wc+TUyfxX1dKwSKhzXbNILKMZPPRBI1e//0Xapb3WD8/rrcBohTEOIqKG7oU+G4RbdioAUd56PMYolBvF6s9vKlmQafdyAOB/hILdOIcL1NuqPjn9YddpZYv6MwTo56qd3HG1QC+BksQ4dhE6fUSf9KQmo2N2JgoL5W0Etqddaq9FippTIJ+I6XzBcxbSACgEC9IL0q5+rTQM0VCGj0hF3jybeXVvA0sdIjMu5jxqUvqwHZb05bZ1OtVQ3WCdV/7CaIYfMherHg0tu+ySIDPBP/q3eTbY22X17X8Dlx8lVMpsS06Cvb29aJDhyxtRCSmfjSRnyyM+YV8rpsWoKQY8+XXUCv9HB9uuE49dXzhq5ACvqzuzVGCVJTeA3yg=
      file: "$DIST_DIR_GITHUB/$GITHUB_RELEASE_FILENAME"
      skip_cleanup: true
      name: "$TRAVIS_TAG"
      on:
        tags: true
    - provider: script
      script: bash travis/deploy-wordpress.sh
      skip_cleanup: true
      on:
        tags: true
notifications:
  slack:
    rooms:
    - secure: bmoIugz9sorNakDw7LnfC3iB7a4CnhuZeZBAVxefSoqipbZAGLoA86pSaDwSK3kNsCRAUXyHJ0pBxxJuCO5jrQKhl9TNBFQQ60KPvn3LQj9OXXTSHp4qoqBytipQGyjeqySu4fJt8Lc0u8FQ0qinxn21qF7K7c54aygVKQd+nxf/+9rVzSOJIY+c6UEBb9FwKfHl9cOJy8nTHYPNl0ZbQaYVS1gvyOV2jzrlurOXb0t2xYs2W9EOAjUd2E4ZVaD8EEyRZ9zcvy8ne41qZGBLMJjHZo6TdN4x0AdEYiITst5fKj+YILNCaVQMyURu5h65RPVXyjZ/eIOUixSt1EOpMTxWcRiDn3H7B2F7eEUIXyo/c5x1AEWEQFLGK+/PEqWx/zaBG0rJJdzVbLaqet2kg5piy+f84EBCZiXm7CZIYPMSjLJo9AJDcY9iSRgvpRnkSagHZAgMILNut53aNPd8i3FoOeycPwux/KDQpSz0uIpn4xu26VY0bzxJ8N27VugUhmNhLCN05Hgw8GoDjEoh4EgPPsdNVzXT4mzpjx2GfhRZOm/78LUSDB/w3oIAEPzRFfhberBAo0l2w9T5+Ynbw9yyquYgNUOW/nMhbwqOPbWqndHa8Xume0DXp2COHEqoSZx4gDIIRRKjKdsrFjjasWB5K7IQXQfBoiGAL7EscNA=
    on_success: change
  email: false
