language: php

php:
- '7.1'
env:
  global:
  - ZIP_FILENAME=list-locations-bmlt-build${TRAVIS_BUILD_NUMBER}-${TRAVIS_COMMIT}.zip
  - S3_BUCKET=archives.bmlt.app
  - S3_KEY=list-locations-bmlt
jobs:
  include:

  - stage: lint
    install:
    - composer install
    script:
    - find . -name "*.php" ! -path '*/vendor/*' -print0 | xargs -0 -n1 -P8 php -l
    - vendor/squizlabs/php_codesniffer/bin/phpcs --warning-severity=6 --standard=PSR2 --ignore=vendor --extensions=php --report=summary ./
  - stage: zip file
    env:
    - BUILD_DIR=build
    - DIST_DIR_S3=dist/s3
    - DIST_DIR_GITHUB=dist/github
    - GITHUB_RELEASE_FILENAME=list-locations-bmlt.zip
    script:
    - find ./ -type d | xargs chmod 755
    - find ./ -name '*.php' | xargs chmod 644
    - zip -r $ZIP_FILENAME list-locations-bmlt && mkdir $BUILD_DIR && mv $ZIP_FILENAME $BUILD_DIR/
    before_deploy:
    - chmod +x travis/deploy-wordpress.sh
    - mkdir -p $DIST_DIR_S3 && cp $BUILD_DIR/$ZIP_FILENAME $DIST_DIR_S3/$ZIP_FILENAME
    - mkdir -p $DIST_DIR_GITHUB && cp $BUILD_DIR/$ZIP_FILENAME $DIST_DIR_GITHUB/$GITHUB_RELEASE_FILENAME
    deploy:
    - provider: s3
      access_key_id: AKIAI7JHYFA6DI3WYP5A
      secret_access_key:
        secure: f38TrHh3t1bsVGGfrRPJrpk2sU+DY09JJguL/kS8Ig/Z2JGNdJP+nlldQ2y52A3EA0s95PtrBrfc6zKfOrGI+ACigatWVMmP+EdcMlFruoEQTBe0sJmnc0dNsbdqvIxKLrKwkfq/NtpY6aKJRhczEcePnzlDCoDGb5WBI5zXYr7SrQh8Q1AlKbG7+zhSd/E/PVLsPNUuFaV1U30HZtAGRiiY7ej9hjHJuZSRW2zM0PRmExS1q2n5LrADUwWXU3OOMQXycrmuZTtJ90NiCkGHexRtlT4/7HELyIcR9fKhBSEbyGPY3U/bWTDEJAL2zz9vGQ4zOeG1a+KuDjzL8rdrSfy0TF4AsMIVheBhHz0jcht/yH9Sg0+O9UyZT5RNbEfL3UWldp5344hvWOsoxD/SeKLIsDsgy3D+I0BLzWDeWzP57Vx5tXHdDbnksnvEWHdrNq7UDJoZFDkiZ9nlp9JnwFzdmI/t5X5emufb3rbaS1/CXWbq70akNF+ThYqzquALCj3lF1zm4/KiVVZo0i9a97OShy5eHo8L3METeFfyVM0AMqrfWr+P+akE2moITyJXEvePeCqhpiue7mX2p+NPasoIbnoNMvE4DGH6gIEFwQc7sc6tSjhcIaIE2tXu/ylA4NxEJD9wUg8NiNlT/prSIAIAUVKMGVkGznuopPETfdw=
      bucket: "$S3_BUCKET"
      local_dir: "$DIST_DIR_S3"
      upload-dir: "$S3_KEY"
      skip_cleanup: true
      on:
        all_branches: true
    - provider: releases
      api_key:
        secure: omNShqzlR9/OGaTS9uR4uE8rRuc5F1AVL+7wfQmeLfRj/EPpHvCaj/8Hdy8gwwex3eKUm+m/+Uf007rtCGyHtchF/Zme/KUpoA2/BAAvwmXtlr57sngOQTsnOhO0Ilhka3kV/qxcW52akiJ9XcUtWyWVfUDu6+QoIm2ehE2BcdjH7B4v7oTcOl+6j/EVaBGTu6WO992tvBJfwAyVmo7SPnUMh683aHfQdpofcpjKeQtUPJ2Ew0l/Zdk0R2wsNOAEwYGguUd/LuN1G+FNbk5DrW1Ybw4mRJanojvewSQAqQ5wnInLQQIFfyC/qj1gXAHzAi7Tv2O41PRR3c0V98GEY9srMOfgI/Q9nBl5kylNZjnc7C7hvyUusjk0jJjxVskYviqPgOIrj/2URUYqvCVfjpMnAKpfnwU5gIgTj8pUdrBTrdN9dI4yM7AXQy6AX8EF+cn2QDSfDBtr0BMYyQrVir2JU85HZZiWFs6NbwZtpJKLIicHuDHPpTZyWbSb4WWF8+BQNmRUjfMg8kesFbk58jwLBtAnPLTdMC40QAakdhKlqi/EGlZPY6XCDr8lagi1NOIrYJYj5186QgbFMN62TTq1frLHJN/Bc2cFfp54WhKQ6N4tX6plEco8jbW7DUVWmriNnf5kiTU7q5OZmMd1QEt0qejMsm8Dijci+pHKw4Y=
      file: "$DIST_DIR_GITHUB/$GITHUB_RELEASE_FILENAME"
      skip_cleanup: true
      name: "$TRAVIS_TAG"
      on:
        tags: true
    - provider: script
      script: bash travis/deploy-wordpress.sh
      skip_cleanup: true
      on:
        tags: true
notifications:
  slack:
    rooms:
    - secure: bmoIugz9sorNakDw7LnfC3iB7a4CnhuZeZBAVxefSoqipbZAGLoA86pSaDwSK3kNsCRAUXyHJ0pBxxJuCO5jrQKhl9TNBFQQ60KPvn3LQj9OXXTSHp4qoqBytipQGyjeqySu4fJt8Lc0u8FQ0qinxn21qF7K7c54aygVKQd+nxf/+9rVzSOJIY+c6UEBb9FwKfHl9cOJy8nTHYPNl0ZbQaYVS1gvyOV2jzrlurOXb0t2xYs2W9EOAjUd2E4ZVaD8EEyRZ9zcvy8ne41qZGBLMJjHZo6TdN4x0AdEYiITst5fKj+YILNCaVQMyURu5h65RPVXyjZ/eIOUixSt1EOpMTxWcRiDn3H7B2F7eEUIXyo/c5x1AEWEQFLGK+/PEqWx/zaBG0rJJdzVbLaqet2kg5piy+f84EBCZiXm7CZIYPMSjLJo9AJDcY9iSRgvpRnkSagHZAgMILNut53aNPd8i3FoOeycPwux/KDQpSz0uIpn4xu26VY0bzxJ8N27VugUhmNhLCN05Hgw8GoDjEoh4EgPPsdNVzXT4mzpjx2GfhRZOm/78LUSDB/w3oIAEPzRFfhberBAo0l2w9T5+Ynbw9yyquYgNUOW/nMhbwqOPbWqndHa8Xume0DXp2COHEqoSZx4gDIIRRKjKdsrFjjasWB5K7IQXQfBoiGAL7EscNA=
    on_success: change
  email: false
