language: php

php:
- '7.1'
env:
  global:
  - ZIP_FILENAME=list-locations-bmlt-build${TRAVIS_BUILD_NUMBER}-${TRAVIS_COMMIT}.zip
  - S3_BUCKET=archives.bmlt.app
  - S3_KEY=list-locations-bmlt
jobs:
  include:

  - stage: lint
    install:
    - composer install
    script:
    - find . -name "*.php" ! -path '*/vendor/*' -print0 | xargs -0 -n1 -P8 php -l
    - vendor/squizlabs/php_codesniffer/bin/phpcs --warning-severity=6 --standard=PSR2 --ignore=vendor --extensions=php --report=summary ./
  - stage: zip file
    env:
    - BUILD_DIR=build
    - DIST_DIR_S3=dist/s3
    - DIST_DIR_GITHUB=dist/github
    - GITHUB_RELEASE_FILENAME=list-locations-bmlt.zip
    - PLUGIN="list-locations-bmlt"
    - MAINFILE="list-locations.php"
    script:
    - find ./ -type d | xargs chmod 755
    - find ./ -name '*.php' | xargs chmod 644
    - zip -r $ZIP_FILENAME ./ -x "*.git*" -x "*.editorconfig*" -x "*.travis.yml*" -x "*assets*" -x "*vendor*" -x "composer.*" -x "*.gitattributes" && mkdir $BUILD_DIR && mv $ZIP_FILENAME $BUILD_DIR/
    before_deploy:
    - mkdir -p $DIST_DIR_S3 && cp $BUILD_DIR/$ZIP_FILENAME $DIST_DIR_S3/$ZIP_FILENAME
    - mkdir -p $DIST_DIR_GITHUB && cp $BUILD_DIR/$ZIP_FILENAME $DIST_DIR_GITHUB/$GITHUB_RELEASE_FILENAME
    - curl -LO https://raw.githubusercontent.com/bmlt-enabled/bmlt-wordpress-deploy/master/deploy-wordpress.sh
    - chmod +x deploy-wordpress.sh
    deploy:
      - provider: s3
        access_key_id: AKIA3EWZC3OHKYCL5SIY
        secret_access_key:
          secure: nLJ9oR4Qy9hiugh2nPUeXo0qIK8SuK5jv4BZ/xO0qEU2KlCcSE0swOCA9CohDWg2po9c7loof6VXQ/8Smb009r4/RUyI5RfAvfhJxuBvVN7q53XvtWzjnJzn1FburXEDbjRC3uTdXoKa5+GUPtv6g9KFOLJu3y9VgecObngtP8+wRtIcTgx9kvPk/v4cKLss6+gBfvxvFoNz8P/nXVT7jJMsf/GVtaGXTJG95IVWeSsFLwtAp5+5cCyUdmfv5Wg/kpm0hLdK0o/hB8FqtGPwAEI6VF5kaH6+Kr9oyJAiYDvuzsdOTC6+h9C2Gd7B17+GT2+a2fFx8lL9aZ7byGqMT8ZUG2FbjxPg76HK1IXIA6TKqTBLQ0jrM85HSvI/WxgMvRnG8osrBhw9BW7H21IY+btYrBhT83kVT80R/YJ5yS0pytM25w0m6IvhxXdjZtkpONLtMKbzI7Wce2VaIkiY50EZfGdMte4WjPP7bNEbvHL+eMoWYdzmK6eGAWefQ1x1VIfKoB4lSO0svjvKybjZKuWEWXsYUxOC+sNjYQ6wYJUVBhpFKsjLI6J7TNNnM/NUBxS05DLfHzJh1cxCcnly8u0FMPfEazk27SA/VWrlfPiyC+gGvU8uovDPOnQsQSwUzRtHxBuoqFApRbXR04aBPvPQUK/qgC+cszryk+CIYsE=
        bucket: "$S3_BUCKET"
        local_dir: "$DIST_DIR_S3"
        upload-dir: "$S3_KEY"
        skip_cleanup: true
        on:
          all_branches: true
      - provider: releases
        edge: true
        token:
          secure: DgyOfJ9hf1001dzIO5om2X4dZG1Dc1NoY6rzxLUQ+teAUO7xWVKvr8rXW6cGme9Mf1VG+CFF2lP8iuY1jcCokh5czdxpBhegA0xqonvJp8V5/dtqAJu8aZicyE0Nt2AF+kwwEVxpQooak+Ti2gq3cJHXF+LlMC1xCX/hElNt6klATSRqQNuYMqpmYtURvao0MUGOhTfevW23raLSVjWWRcDl4ZTdf4TpGcG0pn+cbYi21KLK89oz4rJcVnZQVZDcnfwLbkqiWO+kzJIqua7m8PauHtf0D4hoV52epUhYQM8Z7UBPSUTrR/42yGu+lDN6T3BD9LFAcKII6BiCSJfQl34709dY1gzGAiGvG3LLY3W2pwzgN1JBwX3mgp0Y5gPnazZLAYMrmIcac7i7lxmX53w8cWDY1Gxek7AjSuPNHB6QgwT0JMF0PnMalduOZ7jv45VmDcNamr1SmJ6H2r/zy64i7QaI74UmZkJUJeh5uPfpts9ibP0AU++KEBnx/f0e1blfZa2xlis6GZMp6OXGyWrEJQs8SOlAD1BXC37IKkSIllR7vJWU8t//74EpOTFjqhr4SCDLzEYLoTnsA154PdX+1qxqftrsCY97fwX6LZn1sgwsm3VH7XzcjVggJPQQOw9s0ygaU5ykNnD21xBV1tKEptzJlIsnsGuLPfr8LQg=
        file: "$DIST_DIR_GITHUB/$GITHUB_RELEASE_FILENAME"
        name: "$TRAVIS_TAG"
        prerelease: true
        on:
          tags: true
          condition: $TRAVIS_TAG =~ "beta"
      - provider: releases
        edge: true
        token:
          secure: DgyOfJ9hf1001dzIO5om2X4dZG1Dc1NoY6rzxLUQ+teAUO7xWVKvr8rXW6cGme9Mf1VG+CFF2lP8iuY1jcCokh5czdxpBhegA0xqonvJp8V5/dtqAJu8aZicyE0Nt2AF+kwwEVxpQooak+Ti2gq3cJHXF+LlMC1xCX/hElNt6klATSRqQNuYMqpmYtURvao0MUGOhTfevW23raLSVjWWRcDl4ZTdf4TpGcG0pn+cbYi21KLK89oz4rJcVnZQVZDcnfwLbkqiWO+kzJIqua7m8PauHtf0D4hoV52epUhYQM8Z7UBPSUTrR/42yGu+lDN6T3BD9LFAcKII6BiCSJfQl34709dY1gzGAiGvG3LLY3W2pwzgN1JBwX3mgp0Y5gPnazZLAYMrmIcac7i7lxmX53w8cWDY1Gxek7AjSuPNHB6QgwT0JMF0PnMalduOZ7jv45VmDcNamr1SmJ6H2r/zy64i7QaI74UmZkJUJeh5uPfpts9ibP0AU++KEBnx/f0e1blfZa2xlis6GZMp6OXGyWrEJQs8SOlAD1BXC37IKkSIllR7vJWU8t//74EpOTFjqhr4SCDLzEYLoTnsA154PdX+1qxqftrsCY97fwX6LZn1sgwsm3VH7XzcjVggJPQQOw9s0ygaU5ykNnD21xBV1tKEptzJlIsnsGuLPfr8LQg=
        file: "$DIST_DIR_GITHUB/$GITHUB_RELEASE_FILENAME"
        name: "$TRAVIS_TAG"
        on:
          tags: true
          condition: $TRAVIS_TAG != *beta*
      - provider: script
        edge: true
        script: ./deploy-wordpress.sh
        on:
          tags: true
